import type { Metadata } from "next";
import { Hahmlet, Playwrite_DK_Loopet } from "next/font/google";
import "../globals.css";

const hahmlet = Hahmlet({
  variable: "--font-hahmlet",
  weight: ["300", "400", "700"],
  subsets: ["latin", "latin-ext", "vietnamese"],
});
const loopet = Playwrite_DK_Loopet({
  variable: "--font-loopet",
  weight: ["100", "200", "300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hahmlet.variable} ${loopet.variable} antialiased w-dvw h-dvh`}
      >
        {children}
      </body>
    </html>
  );
}
