import type { Metadata } from "next";
import { Hahmlet } from "next/font/google";
import "../globals.css";

const hahmlet = Hahmlet({
  variable: "--font-hahmlet",
  weight: ["300", "400", "700"],
  subsets: ["latin", "latin-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hahmlet.variable} antialiased`}>{children}</body>
    </html>
  );
}
